version: '3'
# NETWORKS
networks:
  traefik_traefik:
    external: true

#SERVICES
services:
  bitwarden:
    image: vaultwarden/server:latest
    security_opt:
      - no-new-privileges:false
    networks:
      - traefik_traefik
    restart: unless-stopped
    expose:
      - "80"
    environment:
      # After you setted up your user(s)
      - "SIGNUPS_ALLOWED=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.entrypoints=web,websecure"
      - "traefik.http.routers.vaultwarden.tls=true"
      - "traefik.http.routers.vaultwarden.service=vaultwarden"
      - "traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.local`)"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
    volumes:
      # Stockage des fichiers Let's encrypt
      - ./data/:/data
