version: "3.7"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./library:/config
      - /media/jadson/drive/media/series:/data/tvshows
      - /media/jadson/drive/media/movies:/data/movies
      - /media/jadson/drive/media/animes:/data/animes
    ports:
      - 8096:8096
    expose:
      - 8096
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=web"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.local`)"
      - "traefik.http.routers.jellyfin.service=jellyfin"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    networks:
      - traefik_traefik

networks:
  traefik_traefik:
    external: true
